### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/pyo3-extension-template#1]
A short list of features I'd like to add at some point.

- [ ] add option for [mixed rust/python layout](https://github.com/PyO3/maturin/?tab=readme-ov-file#mixed-rustpython-projects)
- [ ] add option for publishing project as a crate to crates.io in addition to PyPI
- [ ] add option for choice of license (MIT, Apache, or dual-licensed)
- [ ] add option(s) for nicer generation of project metadata (e.g., something more well-defined than `{{authors}}`)
- [ ] add option for [limited ABI](https://pyo3.rs/v0.13.2/building_and_distribution.html#py_limited_apiabi3)
- [ ] option to use the maturin action instead of CIBuildWheels (#2)
